/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\barrel.glb --output output\barrel.js --transform 
Files: models\barrel.glb [26.81KB] > E:\Downloads\kenney_food-kit\JSX\output\barrel-transformed.glb [5.24KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Food/Models/barrel-transformed.glb`;

export function ModelKennyNLFoodBarrel(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.barrel_1.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload(link)
