/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CogFixed.glb -T 
Files: CogFixed.glb [13.02MB] > F:\My Documents\Sites games\ice-slide\public\models\CogFixed-transformed.glb [8MB] (39%)
*/

import React, { useEffect, useState } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

export function ModelCogFixed(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/CogFixed-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, mixer } = useAnimations(animations, group)

  useEffect(() => {
    if (!actions || animations.length < 32) return
    
    const action = actions[animations[31].name]
    if (!action) return

    action.reset().fadeIn(0.5).play()
    
    return () => action.fadeOut(0.5)
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null} scale={5}>
      <group name="Scene">
        <group name="Object_7" scale={0.004}>
          <primitive object={nodes._rootJoint} />
        </group>
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.cog_shoe} skeleton={nodes.Object_10.skeleton} scale={0.004} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.sellbot_leg} skeleton={nodes.Object_11.skeleton} scale={0.004} />
        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.sellbot_sleeve} skeleton={nodes.Object_12.skeleton} scale={0.004} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.sellbot_blazer} skeleton={nodes.Object_13.skeleton} scale={0.004} />
        <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.cog_hand} skeleton={nodes.Object_14.skeleton} scale={0.004} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.cog_arm} skeleton={nodes.Object_15.skeleton} scale={0.004} />
        <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.cog_neck} skeleton={nodes.Object_16.skeleton} scale={0.004} />
        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.cog_head_flunky} skeleton={nodes.Object_18.skeleton} scale={0.004} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.cog_flunky_glasses} skeleton={nodes.Object_19.skeleton} scale={0.004} />
      </group>
    </group>
  )
}

useGLTF.preload('models/CogFixed-transformed.glb')
