/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ToontownSkybox.glb -T 
Files: ToontownSkybox.glb [104.81KB] > F:\My Documents\Sites games\stop-the-thieves\public\models\ToontownSkybox-transformed.glb [21.66KB] (79%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelToontownSkybox(props) {
  const { nodes, materials } = useGLTF('models/ToontownSkybox-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.TT_sky_1.geometry} material={materials.middayskyB} renderOrder={-1} />
        <mesh geometry={nodes.TT_sky_2.geometry} material={materials.toontown_central_tutorial_palette_4amla_1} renderOrder={-1} />
      </group>
    </group>
  )
}

useGLTF.preload('models/ToontownSkybox-transformed.glb')
