import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Stop the Thiefs/wave_pergola.glb`

export function PergolaModel(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group position={[-0.9, 0, -2]} rotation={[-Math.PI, 0, 0]} scale={0.086}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40_Ceramic_White_0.geometry}
            material={materials.Ceramic_White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_1_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37_Wood_02_0.geometry}
            material={materials.Wood_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_20_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_23_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31_Wood_02_2_0.geometry}
            material={materials.Wood_02_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34_Wood_02_3_0.geometry}
            material={materials.Wood_02_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35_Wood_02_3_0.geometry}
            material={materials.Wood_02_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38_Wood_02_3_0.geometry}
            material={materials.Wood_02_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39_Wood_02_3_0.geometry}
            material={materials.Wood_02_3}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)